# Para iniciar o container coloque o comando abaixo no terminal:
# docker-compose up -d
version: "3.1"
services:
  postgresql:
    container_name: "lyfm_database"
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: minhasenha
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
